package genericclasses;

import net.bytebuddy.description.type.TypeDescription;
import org.junit.Test;

import java.security.SecureRandom;
import java.util.Random;
import java.util.stream.DoubleStream;
import java.util.stream.IntStream;
import java.util.stream.LongStream;

public class RandomNumbersDemo {
    // Random Number
    // The java.util.Random class is used to generate pseudo-random numbers.
    // Java Random class objects are thread-safe. The instances of this class however are cryptographically insecure.
    // This class provides various methods to generate different random numbers of types such as float, double, int.
    // Random numbers are called pseudo-random numbers when they are generated by some deterministic process,
    // but they qualify the predetermined statistical test for randomness.
    // Constructors:
    // random()                //It creates a new random number generator.
    // random(long seed)       //This creates a new random number generator using a single long seed.
    // A seed is a number, or a vector assigned to a pseudo-random generator to produce the required sequence of random values.
    // If we pass the same seed, it will generate the same sequence. We usually assign the seed as system time.
    // This will produce a different sequence every time.
    // nextInt(int bound)
    //The nextInt(int bound) returns a pseudo random, uniformly distributed int value between 0 (inclusive) and
    // the specified value (exclusive), drawn from this random number generator’s sequence.
    //bound - the upper bound (exclusive). Must be positive.
    //The method throws IllegalArgumentException - if bound is not positive.

    @Test
    public void randomNumberTestOne(){
        Random randomOne = new Random();
        int rdOne = randomOne.nextInt();
        System.out.println("Random number One is: " + rdOne);
        System.out.println();

        Random random = new Random(System.currentTimeMillis());  //Assigning a seed to a Random number generator.
        int rnum = random.nextInt();
        System.out.println("Random number is: " + rnum);
        System.out.println();

        Random randomTwo = new Random(11);
        long rnum3 = randomTwo.nextLong();
        System.out.println("Long number with seed 11: " + rnum3);
        System.out.println();

        float rFloat = random.nextFloat();
        System.out.println("Float Number is: " + rFloat);
        System.out.println();

        int rnum4 = random.nextInt(100);  //Will generate a Random number between 0 - 99.
        System.out.println("Random num with bound 100: " + rnum4);
        System.out.println();

        int rnum2 = random.nextInt(1000);   //Will generate a Random number between 0 - 999.
        String rnum2Format = String.format("%04d", rnum2); //this converts any number sequence into 4 character. But you will get numbers such as 0027.
        //int numResult = Integer.valueOf(rdnFormat);   //When converting the formatted string back to integer, the zeros in front get omitted.
        System.out.println("Random number 2 is: " + rnum2Format);

    }
    @Test
    public void testingRandomNumber(){
        // doubles() method
        //The doubles() method returns an unlimited stream of pseudo random double values,
        // each between zero (inclusive) and one (exclusive).
        Random random = new Random();
        DoubleStream doubleStream = random.doubles();
        System.out.println("Count: " + doubleStream.count());
        //doubleStream.forEach(x -> System.out.println(x));   //Keeps printing unlimited random numbers of double type in the console.
    }

    @Test
    public void testingRandomNumberTwo(){
        // ints() method
        //The ints() method returns an unlimited stream of pseudo random int values.
        Random random = new Random();
        IntStream intStream = random.ints();
        intStream.limit(10).forEach(System.out::println);  //Restricting the unlimited stream to print 10 random numbers only.
        System.out.println();
        //Creating an IntStream with a stream size.
        IntStream intStream1 = random.ints(5);
        System.out.println("IntStream of size 5: ");
        intStream1.forEach(System.out::println);
        System.out.println();
        //Creating LongStream of size 5
        LongStream longStream = random.longs(4);
        System.out.println("LongStream of size 4: ");
        longStream.forEach(System.out::println);
        System.out.println();
        //Creating DoubleStream of size 3.
        DoubleStream doubleStream = random.doubles(3);
        System.out.println("DoubleStream of size 3: ");
        doubleStream.forEach(System.out::println);
    }

    @Test
    public void testingRandomNumberThree(){
        // longs() method
        //The longs() method returns an unlimited stream of pseudo random long values.
        Random random = new Random();
        LongStream longStream = random.longs();  //Better create a stream with Stream size as this stream is unlimited.
        //longStream.forEach(x -> System.out.println(x));  //Prints unlimited random numbers of long type.
        System.out.println("Printing LongStream and limit result to 5: ");
        longStream.limit(5).forEach(System.out::println);
        System.out.println();
    }

    @Test
    public void testingRandomNumberFour(){
        // nextInt()
        //The nextInt() generates the next pseudo random, uniformly distributed int value from this random number generator’s sequence.
        Random random = new Random();
        int num = random.nextInt();
        System.out.println(num);

        // nextInt(int bound)
        //The nextInt(int bound) returns a pseudo random, uniformly distributed int value between 0 (inclusive) and
        // the specified value (exclusive), drawn from this random number generator’s sequence.
        //bound - the upper bound (exclusive). Must be positive.
        //The method throws IllegalArgumentException - if bound is not positive.
        System.out.println();
        int num2 = random.nextInt(99999);
        System.out.println("Random number with bound set to 99999: " + num2);
        System.out.println();
        int num3 = random.nextInt(2);
        System.out.println("Random number with bound 2: ");
        System.out.println(num3);
        System.out.println();
        int num4 = (1 + random.nextInt(2)) * 10000;
        System.out.println("1+random.nextInt(2) * 10000: " + num4);
    }

    @Test
    public void testingRandomNumberFive(){
        //Pseudo Random Number Generator (PRNG)
        //Pseudo Random Number Generator(PRNG) refers to an algorithm that uses mathematical formulas to
        //produce sequences of random numbers. PRNGs generate a sequence of numbers approximating the properties of random numbers.
        //A PRNG starts from an arbitrary starting state using a seed state. Many numbers are generated in
        //a short time and can also be reproduced later, if the starting point in the sequence is known.
        //Hence, the numbers are deterministic and efficient.
        //It is not possible to generate truly random numbers from deterministic things like computers, so PRNG is a technique developed to
        //generate random numbers using a computer. We generate the next random integer using the previous random integer, the integer constants,
        //and the integer modulus. To get started, the algorithm requires an initial Seed, which must be provided by some means.

        Random random = new Random(System.currentTimeMillis());  //Setting up a Seed.
        IntStream intStream = random.ints(23, 26);  //Prints unlimited stream of random int between 23 and 26 exclusive.
        System.out.println(intStream.count());                                          //Numbers can be repeated
        System.out.println();
        IntStream intStream1 = random.ints(23, 35);  //Why the result comes with some numbers repeated.
        System.out.println("Printing the numbers with a limit set to 4: ");
        intStream1.limit(4).forEach(System.out::println);
        System.out.println();
        int seed = 10;
        random.setSeed(seed);   //Setting up a Seed.
        System.out.println("Seed set to 10: ");
        System.out.println(random.nextInt());
        System.out.println();
        //This time let's set the Stream size with bounds.
        Random random1 = new Random();
        IntStream intStream2 = random1.ints(5, 23, 35);  //Result still comes with some numbers repeated.
        System.out.println("Stream size 5, rnOrigine 23, rnBound 35: ");
        intStream2.forEach(System.out::println);

    }

    @Test
    public void testingRandomNumberSix(){
        Random random = new Random();
        //Display 10 random numbers of type int.
        for (int i = 0; i < 10; i++){
            System.out.println("Random number: " + random.nextInt(100));  //Random numbers between 0 and 100 exclusive.
        }                                                                       //Given bigger bound, chances of repeated numbers are small.
    }                                                                           //If given a bound of like 3, of course there will be repeated numbers by
                                                                                //by trying to print 10 random numbers from only 3 possible numbers.

    @Test
    public void testingRandomNumberSeven(){
        //ints(long streamSize, int randomNumberOrigin, int randomNumberBound)
        //This method is used to generate a stream of pseudorandom integer values, which is of the specified size.
        //The specified size is bounded by a lower bound (inclusive) and an upper bound (exclusive).
        //Parameters *******
        //streamSize: This is the size of the stream that needs to be generated.
        //randomNumberOrigin: This is the lower bound (inclusive) for each generated value.
        //randomNumberBound: This is the upper bound (exclusive) for each generated value.
        Random random = new Random();
        IntStream intStream = random.ints(10, 500, 600);
        intStream.forEach(System.out::println);
    }

    @Test
    public void testingRandomNumberEight(){
        //ints(int randomNumberOrigin, int randomNumberBound)
        //This method is used to generate an infinite stream of pseudorandom integer values,
        //each of which adheres to the provided lower bound (inclusive) and upper bound (exclusive).
        //Parameters ******
        //randomNumberOrigin: This is the lower bound (inclusive) for each generated value.
        //randomNumberBound: This is the upper bound (exclusive) for each generated value.
        Random random = new Random();
        IntStream intStream = random.ints(300, 10000);  //Got no repeated number with this code as bound is bigger.
        intStream.limit(10).forEach(x -> System.out.print(x + " "));
    }

    @Test
    public void testingRandomNumberGenerator(){
        Random rdn = new Random(System.currentTimeMillis());  //Setting the Seed to the current system time.

        // The idea is that 1 + nextInt(2) shall always give 1 or 2.
        // You then multiply it by 10000 to satisfy your requirement and
        // then add a number between [0..9999].
        System.out.println((1 + rdn.nextInt(4)) * 10000 + rdn.nextInt(10000));
    }
    @Test
    public void testingRandomNumberGeneratorTwo(){
        Random random = new Random();
        //It generates boolean value
        System.out.println(random.nextBoolean());
        //It generates double value
        System.out.println(random.nextDouble());
        //It generates float value
        System.out.println(random.nextFloat());
        //It generates int value
        System.out.println(random.nextInt());
        //It generates int value within specific limit
        System.out.println(random.nextInt(50));
    }

    public static int getRandomNumberString() {
        // It will generate 6 digit random Number.
        // from 0 to 999999 exclusive
        Random rnd = new Random();
        int number = rnd.nextInt(999999);

        // this will convert any number sequence into 6 character.
        //But you will get numbers such as 000127.
        String format = String.format("%06d", number);  //Test show that after several attempts, we got numbers with 5 digits as well.  to be investigated.
        return Integer.valueOf(format);
        //return String.format("%06d", number);
    }
    @Test
    public void testingTheAbove(){
        System.out.println(getRandomNumberString());
    }

    @Test
    public void testSecureRandom(){
        SecureRandom rands = new SecureRandom();
        //For generating int values we can pass an "upper bound" as a parameter:
        // Generate random integers in range 0 to 999
        int randomNumber1 = rands.nextInt(1000);
        int randomNumber2 = rands.nextInt(1000);

        System.out.println("Random number 1 is: " + randomNumber1);
        System.out.println("Random number 2 is: " + randomNumber2);
        System.out.println();

        //The most common way of using SecureRandom is to generate int, long, float, double or boolean values:
        SecureRandom secureRandom = new SecureRandom();

        int randomInt = secureRandom.nextInt();
        double randomDouble = secureRandom.nextDouble();
        long randomLong = secureRandom.nextLong();
        float randomFloat = secureRandom.nextFloat();
        boolean randomBoolean = secureRandom.nextBoolean();

        System.out.println("integer Random number is: " + randomInt);
        System.out.println("double Random number is: " + randomDouble);
        System.out.println("long Random number is: " + randomLong);
        System.out.println("float Random number is: " + randomFloat);
        System.out.println("boolean Random number is " + randomBoolean);
        System.out.println();

        //In addition, we can generate a stream of values for int, double and long:
        //for all the streams we can explicitly set the size, if we do not we get endless random numbers.
        IntStream randomIntStream = secureRandom.ints(10);
        randomIntStream.forEach(number -> System.out.println(number));
    }

    @Test
    public void moreSecureRandomTests(){
        //For all streams we can explicitly set the stream size, and the origin (inclusive) and bound (exclusive) values as well
        SecureRandom secureRandom = new SecureRandom();
        int streamSize = 10;
        int originValue = 311;
        int boundValue = 333;
        IntStream intStream = secureRandom.ints(streamSize, originValue, boundValue);
        System.out.println("intStream with Stream size, origin value, and bound value : ");
        intStream.forEach(number -> System.out.println(number));
        System.out.println();

        //We can set the seed by using the setSeed() method.  Note: cannot set seed via the constructor: SecureRandom sr = new SecureRandom(5);
        SecureRandom secureRandom1 = new SecureRandom();
        secureRandom1.setSeed(System.currentTimeMillis());
        for (int i = 0; i < 10; i++){
            System.out.println(" Random long number: " + secureRandom1.nextLong());
        }
        System.out.println();
        long lnum = secureRandom1.nextLong();
        System.out.println("long number is: " + lnum);
        System.out.println();
        DoubleStream doubleStream = secureRandom1.doubles(3);
        System.out.println("DoubleStream of 3 numbers: ");
        doubleStream.forEach(System.out::println);
        System.out.println();
        LongStream longStream = secureRandom1.longs(5, 700, 1000);
        System.out.println("Printing longstream of 5, numbers between 700 to 1000: ");
        longStream.forEach(System.out::println);
        System.out.println();

    }
}
